milvus:
  host: 127.0.0.1
  port: 19530
  collection_name: tender_vector_collection
  vector_dim: 4096
  db_name: tender_check
  top_k: 10

minio:
  # .env
  host: 127.0.0.1:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket_name: tender

mysql:
  database_url: mysql+pymysql://root:123456@127.0.0.1:3306/tender_check?charset=utf8mb4
  pool_recycle: 300

llm_model:
  llm_url: https://api.siliconflow.cn/v1/chat/completions
  llm_model_name: Qwen/Qwen3.6-35B-A3B
  api_key: sk-sdbwgllpqhbnijbotgyqsikuhowhmmuzpowxraulvasfexsv

embedding:
  url: https://api.siliconflow.cn/v1/embeddings
  model_name: Qwen/Qwen3-Embedding-8B
  api_key: sk-sdbwgllpqhbnijbotgyqsikuhowhmmuzpowxraulvasfexsv