milvus:
  host: 127.0.0.1
  port: 19530
  vector_dim: 4096
  db_name: tender_check
  top_k: 10

minio:
  host: 127.0.0.1:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket_name: tender

mysql:
  database_url: mysql+pymysql://root:123456@127.0.0.1:3306/tender_check?charset=utf8mb4
  pool_recycle: 300
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_pre_ping: true
  echo: false

llm_model:
  llm_url: https://api.siliconflow.cn/v1
  llm_model_name: Qwen/Qwen3.6-35B-A3B
  api_key: sk-sdbwgllpqhbnijbotgyqsikuhowhmmuzpowxraulvasfexsv
  temperature: 0
  max_tokens: 1000
  timeout: 30
  extra_body:
    enable_thinking: False

embedding:
  url: https://api.siliconflow.cn/v1
  model_name: Qwen/Qwen3-Embedding-8B
  api_key: sk-sdbwgllpqhbnijbotgyqsikuhowhmmuzpowxraulvasfexsv

orc_model:
  url: https://api.siliconflow.cn/v1
  model_name: Qwen/Qwen3.6-35B-A3B
  api_key: sk-sdbwgllpqhbnijbotgyqsikuhowhmmuzpowxraulvasfexsv

mineru:
  load_balance:
    algorithm: weighted_round_robin
  nodes:
    - url: https://uu872443-9142-d8f3a5ba.bjb2.seetacloud.com:8443/file_parse
      weight: 1
    - url: https://uu872443-9142-d8f3a5ba.bjb2.seetacloud.com:8443/file_parse
      weight: 1
    - url: https://uu872443-9142-d8f3a5ba.bjb2.seetacloud.com:8443/file_parse
      weight: 1
    - url: https://uu872443-9142-d8f3a5ba.bjb2.seetacloud.com:8443/file_parse
      weight: 1
  data:
    # server_url: http://vllm-server:8000
    backend: hybrid-auto-engine
    table_enable: True
    parse_method: auto
    lang_list: ch
    return_images: True
    return_middle_json: True
    return_content_list: True

tender_check:
  text_overlap_threshold: 0.3
  vector_similarity_threshold: 0.85

file:
  https:
  http: