services:
  web-app:
    container_name: tender-check
    image: tender:v3.1
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "30018:8000"
    volumes:
      - ./:/app/tender
